# Generated by Django 5.1.3 on 2025-01-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amzonproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custemdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('disctict', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
