# Generated by Django 5.1.3 on 2025-01-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amzonproduct', '0003_custemdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custemdetails',
            name='name',
        ),
    ]
